### ISSUE TITLE
How Update Nameservers When Using Custom DNS

### ISSUE THREAD

**Issue by dovidgef** [namecheap/terraform-provider-namecheap#35]
Hi, how could I update a domains nameservers using this provider?

Lets say I would like to switch managing DNS to a different third party DNS provider?

Thanks

**Comment by DomWeldon** [comment]
Just to add to this, it seems this provider is focused primarily around using Namecheap's own DNS features, whereas, I simply use Namecheap as my DNS registrar but then manage all my DNS config through Route 53. A cursory browse of thee Namecheap API seems to suggest that there are lots more methods which can be added to the provider than just those currently implemented by this provider.

The most urgent from my perspective would be [`setCustom`](https://www.namecheap.com/support/api/methods/domains-dns/set-custom/), however, I'm not sure how this interfaces with `setDefault`, and it looks like we may need some thoughts as to how to design the provider interface given the constraints of the API.

@adamdecaf - do you have any thoughts or plans on this? I'm not super familiar with Go, but reckon I could have a decent stab at this in the next couple of weeks. Do you have any rough thoughts on a spec for this part of the provider as yet?

**Comment by StyleT** [comment]
I suppose that it should be addressed in #46 or soon after it

**Comment by ifree92** [comment]
Please have a look here: https://registry.terraform.io/providers/namecheap/namecheap/latest/docs/guides/namecheap_domain_records_guide#nameservers

This is a way how to set custom nameservers.
