### ISSUE TITLE
This provider isn't production ready / this provider has big issues

### ISSUE THREAD

**Issue by awoimbee** [namecheap/terraform-provider-namecheap#45]
### Terraform Version
```
Terraform v0.15.4
on linux_amd64
```

### Namecheap provider version
`robgmills/namecheap 1.7.0`

### My goal

The goal is not to be mean, but to make the maintainers realise (if they don't already) how bad this provider is, from the perspective of a user.
Also, this does not look like some sort of open source project with maintainers that work for free, this is direct from the namecheap github org, so I expect much better than this.

### Issues

- Why do I need to give my IP ? Can't the namecheap server figure it out ?! 
  Why do I have to create `terraform.sh`:
  ```bash
  NAMECHEAP_IP="$(curl -s ifconfig.me)" terraform $@
  ```
- `Could not find the record with hash 123456789` happens all the time ! I can't trust this thing to run unsupervised, it's faster to use the web app because at least I know it won't crash !
- Why do I need to use `robgmills/namecheap` ? Isn't the git repo `namecheap/terraform-provider-namecheap` ?
  Why am I running v1.7.0 when the latest release on `namecheap/terraform-provider-namecheap` is 1.6.0 ?
- Knowing how buggy this thing is, why is it at `1.7.0` and not `0.1.7` ? Why isn't there a disclaimer "not ready for production use" ?

**Comment by ifree92** [comment]
Hi @awoimbee 

Thanks for interest and report. Much appreciated.

We just transfered this repo under our support in less than 1 week and just about to start a complete revision, refactoring, wrapping with a correct tests and general stabilisation.

Please bear with us, we will update you ASAP. Probably @StyleT will add a few words

**Comment by adamdecaf** [comment]
(Speaking as an individual, I'm not affiliated with Namecheap)

I started this project after needing to set a couple DNS records with namecheap. I found a Go library someone else wrote, adopted it and built this provider to my personal needs. After a couple years of volunteering support on nights and weekends I offered it to Namecheap who accepted it last week because my day job needed most of my energy. Namecheap is working on making the provider awesome, but you'll need to give them patience and come with a better attitude.

**Comment by awoimbee** [comment]
Thanks for the quick and professional responses. I changed the title for something more suitable (the original one did its job of getting a reaction).
Thanks for creating this provider. While I think it's not ready yet, I still think it's very cool that it exists.

The original issue about this provider working 1/3 times, having no disclaimer that it's not ready, and the weird situation with the README telling users to install `robgmills/namecheap` still stands tho.

**Comment by ifree92** [comment]
@awoimbee Anyway, thanks for reporting any issues, that will help us to figure out faster and understand the current state of things

**Comment by StyleT** [comment]
I suppose that some/all of the issues should be addressed in #46

**Comment by ifree92** [comment]
@awoimbee thanks for your patience and report.
We have been published our new v2 major release, please have a look
https://registry.terraform.io/providers/namecheap/namecheap/latest/docs

The only issue from your list that requires additional consideration is the client IP address exposure. We will return to this point soon.

Right now I'm closing the issue.

**Comment by benmezger** [comment]
@ifree92 did you end up returning to the IP issue? The IP issue is really a problem since we can't run in a CI/CD. We had to completely disable + delete Namecheap from our state, because of this :(
