### ISSUE TITLE
Domain name not found with FreeDNS domain

### ISSUE THREAD

**Issue by tranvansang** [namecheap/terraform-provider-namecheap#60]
I am migrating to namecheap provider v2.0.
The v2.0 has a problem with FreeDNS domains and it is currently blocking me.
Please have a look at this.
Thank you.

### Terraform Version
```
Terraform v1.0.9
on linux_amd64
```

### Namecheap provider version

`2.0.1`

### Affected Resource(s)

- `namecheap_domain_records`

### Terraform Configuration Files

NOTE: `transa.ng` is a FreeDNS domain. (I bought it from another DNS provider and control it within namecheap)

```hcl
resource namecheap_domain_records "main" {
	domain = "transa.ng"
	mode   = "OVERWRITE" # or "MERGE", whichever won't work

	record {
		hostname = "@"
		type     = "A"
		address  = "1.2.3.4"
	}
}
```

### Debug Output
The debug output includes too much sensitive information. I only include the related portion here. It is short, so I paste it directly.
```
namecheap_domain_records.main: Refreshing state... [id=transa.ng]
2021-10-26T10:36:22.178+0900 [TRACE] GRPCProvider: ReadResource
2021-10-26T10:36:22.895+0900 [TRACE] vertex "namecheap_domain_records.main": visit complete
2021-10-26T10:36:22.895+0900 [TRACE] vertex "namecheap_domain_records.main": dynamic subgraph encountered errors: Domain name not found (2019166)
2021-10-26T10:36:22.896+0900 [TRACE] vertex "namecheap_domain_records.main": visit complete
2021-10-26T10:36:22.896+0900 [TRACE] vertex "namecheap_domain_records.main (expand)": dynamic subgraph encountered errors: Domain name not found (2019166)
2021-10-26T10:36:22.896+0900 [TRACE] vertex "namecheap_domain_records.main (expand)": visit complete
2021-10-26T10:36:22.896+0900 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/namecheap/namecheap\"] (close)" errored, so skipping
2021-10-26T10:36:22.896+0900 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021-10-26T10:36:22.896+0900 [TRACE] dag/walk: upstream of "root" errored, so skipping
╷
│ Error: Domain name not found (2019166)
│ 
│   with namecheap_domain_records.main,
│   on main.tf line 1, in resource "namecheap_domain_records" "main":
│    1: resource namecheap_domain_records "main" {
│ 
╵
```

### Expected Behavior

It should run `terraform plan` successfully.

### Actual Behavior

The first run is ok.
But from the second run, the provider fails to run, with the error

`Error: Domain name not found (2019166)`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply -auto-approve`
2. `terraform plan` (without any change to the configuration)

### Important Factoids
NOTE: `transa.ng` is a FreeDNS domain. (I bought it from another DNS provider and control it within Namecheap).

**Comment by tranvansang** [comment]
Hello, namecheap has taken this project and maintained it officially.

However, this issue is blocking me.
I cannot use any FreeDNS domain at all.

Is there any update about this?

@ifree92

**Comment by StyleT** [comment]
Hi!
I'll take a look at this somewhere this week.

**Comment by tranvansang** [comment]
Hello. Is there any update on this?

**Comment by StyleT** [comment]
> Hello. Is there any update on this?

Hi! Sorry for the delay (we had internal staff changes that affects this project). It's in the pipeline at the moment. Hope to have it fixed very soon.

**Comment by StyleT** [comment]
Hello @tranvansang 

I just tested the provider version personally. And it works fine for me with FreeDNS domain actually.

Could you pls take a full screenshot of the page https://ap.www.namecheap.com/Domains/DomainControlPanel/transa.ng/advancedns ?

And give me full provider configuration that you're using (except for api_key of course).

**Comment by tranvansang** [comment]
![screencapture-ap-www-namecheap-Domains-DomainControlPanel-transa-ng-advancedns-2021-11-26-22_51_28](https://user-images.githubusercontent.com/13043196/143591015-3ee3282d-c12b-4aa3-9966-74060bad6629.png)

**Comment by tranvansang** [comment]
```terraform
resource namecheap_domain_records "main" {
	domain = local.domain
	email_type = "OX"
	mode   = "MERGE"

	record {
		hostname = "@"
		type     = "A"
		address  = jsondecode(file("../../../config/global.json")).vultr-server-ip-prod
	}
	record {
		hostname = "www"
		type     = "A"
		address  = jsondecode(file("../../../config/global.json")).vultr-server-ip-prod
	}

	# google search
	record {
		hostname = "@"
		type     = "TXT"
		address  = "google-site-verification=rN6yjiyhKh0Mt4jC9OrgSGLokfD1fw5Ba18onhrczrQ"
	}
}

locals {
	domain = "transa.ng"
}

terraform {
	backend "s3" {
		bucket                  = "transang-terraform-state"
		key                     = "transa.ng/common/namecheap/terraform.tfstate"
		region                  = "ap-northeast-1"
		profile                 = "terraform-backend"
		shared_credentials_file = "../../../secrets/transang-aws.credentials"

		dynamodb_table = "terraform-state-lock"
		encrypt        = true
	}
	required_providers {
		namecheap = {
			source  = "namecheap/namecheap"
			version = ">= 2.0.0"
		}
	}
}

provider "namecheap" {
	user_name   = jsondecode(file("../../../secrets/transang-namecheap.json")).user_name
	api_user    = jsondecode(file("../../../secrets/transang-namecheap.json")).api_user
	api_key     = jsondecode(file("../../../secrets/transang-namecheap.json")).api_key
	client_ip   = jsondecode(file("../../../secrets/transang-namecheap.json")).client_ip
	use_sandbox = false
}

```

**Comment by StyleT** [comment]
Hi!
Could you specify what you have in `user_name` and `api_user` for provider?

Error looks like you're trying to use wrong user to access domain. This error comes from public Namecheap API and is described here: https://www.namecheap.com/support/api/error-codes/ (search for "2019166" error code ob the page).

During my test I set `user_name` and `api_user` to the same value of my NC username I use for sign in.

**Comment by tranvansang** [comment]
```json
{
	"user_name": "transang",
	"api_user": "transang",
	"api_key": "***masked***",
	"client_ip": "125.14.75.67"
}
```

I only use one credential for login. This credential works with other (non freedns) domains.

Moreover, **terraform runs normally in the first run, but fails from subsequent runs, even with `terraform plan`**

**Comment by StyleT** [comment]
Now I got the same error, thx. Will continue next week ;)

**Comment by tranvansang** [comment]
It works now. Thanks!
