### ISSUE TITLE
Nameserver array missing trailing dot

### ISSUE THREAD

**Issue by ams0** [namecheap/terraform-provider-namecheap#69]
Hi there,

thank you for the provider, it really helped coming up with this repo: https://github.com/ams0/namecheap-azure-terraform where I use Azure DNS and Namecheap. My only issue is that every time I run `tf plan`, the run will force new values for the name servers:

```
    ~ nameservers = [
          - "ns1-38.azure-dns.com",
          + "ns1-38.azure-dns.com.",
          - "ns2-38.azure-dns.net",
          + "ns2-38.azure-dns.net.",
          - "ns3-38.azure-dns.org",
          + "ns3-38.azure-dns.org.",
          - "ns4-38.azure-dns.info",
          + "ns4-38.azure-dns.info.",
        ]
```

because the array coming from the output of `azurerm_dns_zone.zone[each.key].name_servers` is an array with dots at the end, but internally, namecheaps seems to store the name server without the dot, forcing a change every time. I have no solutions to the problem, I trie the `trim` TF function but it works on strings, not arrays, so I don't know how to strip the dot from each element of an array. It's more annoying than anything, but if someone knows a solution, I'd be very grateful.

**Comment by ams0** [comment]
I could fix it like this (horrible hack):

```
  nameservers = split(" ", trimsuffix(replace(join(", ", azurerm_dns_zone.zone[each.key].name_servers), ".,", ""), "."))

```

but still...

**Comment by adamdecaf** [comment]
Can you `sort()` the array of strings? 

https://www.terraform.io/language/functions/sort

**Comment by ams0** [comment]
a bit better:

```
  nameservers = [for entry in azurerm_dns_zone.zone[each.key].name_servers : trimsuffix(entry, ".")]
```

So I'm happy now, but just want to leave this here in case someone needs this little piece on info to make Namecheap+AzureDNS work together
