### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by maelp** [namecheap/terraform-provider-namecheap#70]
### Terraform Version
Terraform v1.3.4
on darwin_amd64

### Namecheap provider version
+ provider registry.terraform.io/namecheap/namecheap v2.1.0

### Terraform Configuration Files
```hcl
provider "namecheap" {
  api_key   = var.namecheap-api-key
  api_user  = "username as what is shown in my account menu on the website"
  user_name = "a user name"
  use_sandbox = false
}
```

### Expected Behavior
I should be able to create a DNS record

### Actual Behavior
Error

```
Error: Username does not exist (1019103)
```

### Steps to Reproduce
`terraform apply`

**Comment by vetal2409** [comment]
Please, check that you set the correct `user_name`. This is the  Username on which a command is executed. Generally, the values of the ApiUser and UserName parameters are the same.

Documentation
https://www.namecheap.com/support/api/global-parameters/

It should work currently but if you still struggling with this problem, please, provide more details and we will try to help you!
